### ISSUE TITLE
Part preview out of view mobile 

### ISSUE THREAD

**Issue by fhareide** [ldraw-org/ldraworg-library#77] opened 2023-02-05 06:00 UTC
The part preview modal overflows the screen on mobile. 
![Screenshot_20230205_065834_Chrome](https://user-images.githubusercontent.com/12023679/216804307-aea8641b-2963-4389-87ba-5bbae9241599.jpg)

**Comment by ldraw-org** [comment] 2023-02-05 19:24
Duplicate of #46.

**Closed by ldraw-org** 2023-02-05 19:24 UTC
